### ISSUE TITLE
thirdsdk无法安装

### ISSUE THREAD

**Issue by YuanyeChi** [aqi00/android2#1]
![image](https://user-images.githubusercontent.com/37322570/58150358-fb082900-7c98-11e9-936a-39d221587f76.png)
05/22 05:51:47: Launching thirdsdk
$ adb install-multiple -r -t D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_9.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_8.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_2.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_5.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_4.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_3.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\dep\dependencies.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_6.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_1.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_0.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_7.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\resources\instant-run\debug\resources-debug.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\instant-run-apk\debug\thirdsdk-debug.apk 
$ adb shell pm uninstall com.example.thirdsdk
Unknown failure: Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.example.thirdsdk
at com.android.server.pm.Settings.isOrphaned(Settings.java:4289)
at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21095)
at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:17916)
at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:736)
at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
at android.os.ShellCommand.exec(ShellCommand.java:103)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21328)
at android.os.Binder.shellCommand(Binder.java:634)
at android.os.Binder.onTransact(Binder.java:532)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
at android.os.Binder.execTransact(Binder.java:731)
Error while Installing APKs

**Comment by aqi00** [comment]
直接安装到真机上，不要在模拟器上安装。因为模拟器依赖于电脑的指令集，该模块用到的so库可能不兼容某些电脑的cpu指令






At 2019-05-22 13:56:18, "tsiye" <notifications@github.com> wrote:



05/22 05:51:47: Launching thirdsdk
$ adb install-multiple -r -t D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_9.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_8.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_2.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_5.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_4.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_3.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\dep\dependencies.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_6.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_1.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_0.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\split-apk\debug\slices\slice_7.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\resources\instant-run\debug\resources-debug.apk D:\AndroidStudioProjects\android2-master\thirdsdk\build\intermediates\instant-run-apk\debug\thirdsdk-debug.apk
$ adb shell pm uninstall com.example.thirdsdk
Unknown failure: Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.example.thirdsdk
at com.android.server.pm.Settings.isOrphaned(Settings.java:4289)
at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21095)
at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:17916)
at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:736)
at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
at android.os.ShellCommand.exec(ShellCommand.java:103)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21328)
at android.os.Binder.shellCommand(Binder.java:634)
at android.os.Binder.onTransact(Binder.java:532)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
at android.os.Binder.execTransact(Binder.java:731)
Error while Installing APKs

**Comment by YuanyeChi** [comment]
好的谢谢！
